services:
  db:
    image: mysql:8.1
    container_name: polls_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: polls_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: polls_phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "8080:80"

  redis:
    image: redis:7-alpine
    container_name: polls_redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    image: atakowiec/polls-backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: supersecretkeygoeshere
      MYSQL_HOST: db
      MYSQL_DATABASE: polls_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
      REDIS_URL: redis://redis:6379/0

  frontend:
    image: atakowiec/polls-frontend
    container_name: frontend
    ports:
      - "3000:3000"